version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='djangodocker'
      - MYSQL_USER='admin'
      - MYSQL_PASSWORD='Panadero90*'
      - MYSQL_HOST='teis20251.clyzhlrzws4e.us-east-1.rds.amazonaws.com'
      - MYSQL_ROOT_PASSWORD='123456789'
    volumes:
      - /tmp/code/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/code/mysqld:/run/mysqld
    depends_on:
      - db